# Generated by Django 3.2.4 on 2022-07-25 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FUApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='upload',
            name='profile_pic',
            field=models.ImageField(blank=True, null=True, upload_to='media/uploads/', verbose_name='Profile Photo'),
        ),
    ]
